version: "3.9"

services: 
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "443:443"
    volumes:
      - ./frontend/configs/:/usr/share/nginx/html
      - ./backend/api:/api
    networks:
      - transcendence
    restart: always

  backend:
    container_name: django
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/api:/api 
    networks:
      - transcendence
    restart: always

networks:
  transcendence: