version: "3.9"

services: 
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "443:443"
    volumes:
      - ./backend/server:/usr/share/nginx/html
    networks:
      - transcendence
    restart: always

  backend:
    container_name: django
    build: ./backend
    networks:
      - transcendence

networks:
  transcendence: